# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "sweh.la"
license = "GPLv3"
licenselink = "https://github.com/lordspacehog/sweh.la/blob/master/LICENSE.md"
description = ""
homepage = "http://sweh.la/"
tags = ["", ""]
features = ["", ""]
min_version = 0.13

[author]
  name = "alex swehla"
  homepage = "alex.sweh.la"
